[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' https://cdnjs.cloudflare.com/ 'unsafe-inline'; script-src 'self' https://cdnjs.cloudflare.com/ 'unsafe-inline'; img-src 'self' https: data:; font-src 'self' https: data:; frame-ancestors 'self'"
